version: "3.9"

services:

  api-gateway:
    build: ./api-gateway
    container_name: a11ypulse-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - audit-service
      - metrics-service
    networks:
      - a11ypulse-network

  audit-service:
    build: ./audit-service
    container_name: a11ypulse-audit-service
    ports:
      - "8081:8080"
    networks:
      - a11ypulse-network

  metrics-service:
    build: ./metrics-service
    container_name: a11ypulse-metrics-service
    ports:
      - "8082:8080"
    networks:
      - a11ypulse-network

networks:
  a11ypulse-network:
    driver: bridge
